### ISSUE TITLE
Spelling typo on app landing page under "Data Visualization"

### ISSUE THREAD

**Issue by kfoofw** [Rulisetiawati/COVID-vaccine-sentiment-analysis#10]
Hi guys, the app looks great! I just wanted to point out some spelling error typo under the Data Visualization section of your app.

I think it should be "Neutral" instead of "Nuetral".

![image](https://user-images.githubusercontent.com/7871453/111084896-ee8a3b80-84d1-11eb-9edd-338b197dacb1.png)

Awesome job by the way! :)

**Comment by eqdcheng** [comment]
Fixed, thanks! :)
